"""Notebook setup and teaching helper functions."""

from .helpers import (
    build_cell_for_notebook,
    build_synapse_test_cell,
    ensure_external_repo_on_syspath,
    ensure_scp_repo_on_syspath,
)
from .bootstrap import (
    check_required_external_inputs,
    ensure_modfiles,
    finish_step5_notebook_setup,
    is_colab,
)
from .synapse_preview import show_synapse_preview
from .run_diagnostics import show_run_diagnostics
from .pipeline_ui import PIPELINE_UI_DEFAULTS, PipelineNotebookUI
from .pipeline_act import (
    PipelineACTEvaluationResult,
    PipelineACTRunResult,
    PipelineACTWorkspaceResult,
    display_act_evaluation,
    evaluate_fresh_act_predictions,
    inspect_act_active_stage,
    prepare_act_active_stage,
    run_fresh_act_active,
)
from .pipeline_workflow import (
    PipelineActiveProtocolResult,
    PipelineActiveResult,
    PipelineFIResult,
    PipelineInputPreviewResult,
    PipelineNotebookState,
    PipelinePassiveProposalResult,
    PipelinePassiveResult,
    PipelineSimulationResult,
    RestartKernelRequired,
    compute_passive_proposal,
    prepare_interactive_synapse_tuner,
    prepare_pipeline_notebook,
    preview_pipeline_inputs,
    run_active_stage,
    run_active_protocol_stage,
    run_fi_curve_stage,
    run_fresh_simulation,
    run_passive_stage,
)

__all__ = [
    "build_cell_for_notebook",
    "build_synapse_test_cell",
    "check_required_external_inputs",
    "ensure_external_repo_on_syspath",
    "ensure_modfiles",
    "ensure_scp_repo_on_syspath",
    "finish_step5_notebook_setup",
    "is_colab",
    "PIPELINE_UI_DEFAULTS",
    "PipelineNotebookUI",
    "PipelineACTEvaluationResult",
    "PipelineACTRunResult",
    "PipelineACTWorkspaceResult",
    "PipelineActiveProtocolResult",
    "PipelineActiveResult",
    "PipelineFIResult",
    "PipelineInputPreviewResult",
    "PipelineNotebookState",
    "PipelinePassiveProposalResult",
    "PipelinePassiveResult",
    "PipelineSimulationResult",
    "RestartKernelRequired",
    "compute_passive_proposal",
    "display_act_evaluation",
    "evaluate_fresh_act_predictions",
    "inspect_act_active_stage",
    "prepare_interactive_synapse_tuner",
    "prepare_pipeline_notebook",
    "prepare_act_active_stage",
    "preview_pipeline_inputs",
    "run_active_stage",
    "run_active_protocol_stage",
    "run_fi_curve_stage",
    "run_fresh_simulation",
    "run_fresh_act_active",
    "run_passive_stage",
    "show_run_diagnostics",
    "show_synapse_preview",
]
