"""Shared helpers for Step 2/3 tuning notebooks.

The package keeps notebook setup, ACT discovery, passive tuning calculations,
and optional proposal helpers out of user-facing notebook cells. Functions avoid
importing NEURON or ACT at module import time; those dependencies are loaded
only when requested.
"""

from .act_integration import (
    ACT_ENV_VARS,
    ACT_REPO_URL,
    ensure_act_on_syspath,
    import_act_active_api,
    import_act_passive_module,
    resolve_act_repo,
)
from .notebook_setup import (
    Step1ValidationReport,
    TuningNotebookContext,
    build_tuning_cell,
    ensure_repo_on_syspath,
    load_tune_configs,
    prepare_tuning_notebook_context,
    resolve_repo_root,
    resolve_tune_dir,
    section_summary,
    validate_step1_outputs,
)
from .proposals import (
    default_proposal_path,
    proposal_change_rows,
    print_proposal_summary,
    write_tuning_proposal,
)
from .passive import (
    compute_settable_passive_properties,
    iter_cell_sections,
    passive_metric_rows,
    passive_area_summary,
    passive_proposal_changes,
    run_passive_protocol,
    section_area_cm2,
    soma_area_cm2,
    total_area_cm2,
)
from .active import (
    DEFAULT_BIO_FI_REFERENCE,
    active_metric_rows,
    active_trace_metrics,
    fi_rows_from_metrics,
    get_bio_fi_reference,
    plot_active_trace_check,
    plot_fi_curve,
    run_active_protocol,
    spike_times_from_trace,
)
from .allen_nwb import (
    DEFAULT_FI_STIMULUS_NAMES,
    aggregate_fi_sweeps,
    extract_allen_nwb_fi_sweeps,
    summarize_allen_nwb_sweeps,
    write_allen_nwb_fi_target_csv,
)
from .act_active import (
    CONFIG_NAME as ACT_ACTIVE_CONFIG_NAME,
    TARGET_SF_NAME as ACT_ACTIVE_TARGET_SF_NAME,
    BUILDER_NAME as ACT_ACTIVE_BUILDER_NAME,
    collect_act_predictions,
    default_act_active_config,
    default_act_module_specs,
    default_act_workspace,
    default_target_fi,
    evaluate_act_predictions,
    load_act_active_config,
    prepare_act_active_workspace,
    resolve_act_workspace_from_labels,
    run_act_active_module,
    run_act_active_modules,
    workspace_summary,
)
from .bmtool_synapse_adapter import (
    BMTOOL_ENV_VARS,
    BMTOOL_REPO_URL,
    SynapseTuningSession,
    create_scp_synapse_tuner,
    default_record_vars_for_connection,
    default_slider_vars_for_connection,
    ensure_bmtool_on_syspath,
    get_tuned_synapse_params,
    import_bmtool_synapse_api,
    prepare_scp_synapse_tuning,
    print_syn_group_param_block,
)

__all__ = [
    "ACT_ENV_VARS",
    "ACT_ACTIVE_BUILDER_NAME",
    "ACT_ACTIVE_CONFIG_NAME",
    "ACT_ACTIVE_TARGET_SF_NAME",
    "ACT_REPO_URL",
    "BMTOOL_ENV_VARS",
    "BMTOOL_REPO_URL",
    "DEFAULT_BIO_FI_REFERENCE",
    "DEFAULT_FI_STIMULUS_NAMES",
    "Step1ValidationReport",
    "SynapseTuningSession",
    "TuningNotebookContext",
    "active_metric_rows",
    "active_trace_metrics",
    "aggregate_fi_sweeps",
    "build_tuning_cell",
    "collect_act_predictions",
    "create_scp_synapse_tuner",
    "default_record_vars_for_connection",
    "default_proposal_path",
    "default_act_active_config",
    "default_act_module_specs",
    "default_act_workspace",
    "default_slider_vars_for_connection",
    "default_target_fi",
    "ensure_bmtool_on_syspath",
    "ensure_act_on_syspath",
    "ensure_repo_on_syspath",
    "evaluate_act_predictions",
    "extract_allen_nwb_fi_sweeps",
    "fi_rows_from_metrics",
    "get_bio_fi_reference",
    "get_tuned_synapse_params",
    "import_act_active_api",
    "import_act_passive_module",
    "import_bmtool_synapse_api",
    "iter_cell_sections",
    "load_tune_configs",
    "load_act_active_config",
    "prepare_tuning_notebook_context",
    "prepare_act_active_workspace",
    "prepare_scp_synapse_tuning",
    "compute_settable_passive_properties",
    "print_proposal_summary",
    "print_syn_group_param_block",
    "proposal_change_rows",
    "passive_area_summary",
    "passive_metric_rows",
    "passive_proposal_changes",
    "plot_active_trace_check",
    "plot_fi_curve",
    "resolve_act_repo",
    "resolve_act_workspace_from_labels",
    "resolve_repo_root",
    "resolve_tune_dir",
    "run_act_active_module",
    "run_act_active_modules",
    "run_active_protocol",
    "run_passive_protocol",
    "section_summary",
    "section_area_cm2",
    "soma_area_cm2",
    "spike_times_from_trace",
    "summarize_allen_nwb_sweeps",
    "total_area_cm2",
    "validate_step1_outputs",
    "write_tuning_proposal",
    "write_allen_nwb_fi_target_csv",
    "workspace_summary",
]
